name: Release Notification to Slack Channel
author: cschau0701vip
branding:
  icon: message-circle
  color: orange
description: Release Notification to Slack Channel BOT using composite action.
inputs:
  webhook_url:
    required: true
    description: Slack webhook URL
  title:
    required: true
    description: Message title
  body:
    required: false
    description: Message body
  context:
    required: true
    description: Project
runs:
  using: "docker"
  image: "Dockerfile"
  args:
  - ${{ inputs.title}} 
  - ${{ inputs.webhook_url}} 
  - ${{ inputs.body}} 
  - ${{ inputs.context}}
