name: Send message of release on Slack Using Dockerfile

on:
 # push:
 #   branches: [main]
  workflow_dispatch:
    
jobs:
  my-slack-job:
    runs-on: ubuntu-latest
    steps:  
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Use local Action
       # uses: ./     #custom local
        uses: Cschau0701vip/custom-action-using-docker@slack-v1
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          title: ${{ vars.MESSAGE_TITLE }}  # Success!😍
          body: ${{ vars.MESSAGE_BODY }}  # Hello from local action!
          context: ${{ vars.MESSAGE_CONTEXT }}  # Demo
